### ISSUE TITLE
Should pass max_age to  AbstractStorage.save_session()？

### ISSUE THREAD

**Issue by netpie** [aio-libs/aiohttp_session#10]
need different session expiration policies.

**Comment by netpie** [comment]
maybe better to move or copy _max_age to the session object.

**Comment by asvetlov** [comment]
@netpie sorry, I don't follow.
Would you elaborate what API do you need and why?

**Comment by netpie** [comment]
I want to change session's expiration in session_middleware or orther request handler. How to do?
Need API: def save_session(self, request, response, session, max_age = None) 
      If max_age is not None, change current seesion' expiration.

**Comment by asvetlov** [comment]
I think `save_session` is not need new parameter.
`max_age` property in session object should be enough.

**Comment by netpie** [comment]
Thanks!

**Comment by asvetlov** [comment]
Fixed by 320861cbea08a4661bccc3cce7752204090e2708
