### ISSUE TITLE
Not able to invalidate session, using EncryptedCookieStorage

### ISSUE THREAD

**Issue by AlexKovalevych** [aio-libs/aiohttp_session#12]
These lines https://github.com/aio-libs/aiohttp_session/blob/master/aiohttp_session/__init__.py#L161-L162 will never be executed in case of usage EncryptedCookieStorage:

Here https://github.com/aio-libs/aiohttp_session/blob/master/aiohttp_session/cookie_storage.py#L43-L47
in case of empty dict `session._mapping`  variable `cookie_data` is `b'{}              '` and after all transformations `b64coded ` is a hash which is definitely not a `False` boolean value. 

As result condition `if not cookie_data:` will always return `False` and session will not be invalidated.

**Comment by asvetlov** [comment]
Good catch! Would you make Pull Request?

**Comment by AlexKovalevych** [comment]
Issue can be closed now.

**Comment by asvetlov** [comment]
Solved
