### ISSUE TITLE
pip install FileNotFoundError 

### ISSUE THREAD

**Issue by skatsaman** [aio-libs/aiohttp_session#15]
pip install crashed with strace:

(VENV) crwnlssmbp:aiohttp-session soullu$ python ./setup.py install 
Traceback (most recent call last):
  File "./setup.py", line 27, in <module>
    long_description='\n\n'.join((read('README.rst'), read('CHANGES.txt'))),
  File "./setup.py", line 16, in read
    return open(os.path.join(os.path.dirname(__file__), f)).read().strip()
FileNotFoundError: [Errno 2] No such file or directory: './CHANGES.txt'

**Comment by asvetlov** [comment]
Fixed in `0.1.2`
Thanks for report
