### ISSUE TITLE
saving of session doesn't work with `raise HttpFound`, but it works well with `return`

### ISSUE THREAD

**Issue by imbolc** [aio-libs/aiohttp_session#23]
Here is gist I used for test: https://gist.github.com/imbolc/aa0f2cfc89f0a7994e5d

**Comment by asvetlov** [comment]
You are right.
The question is: what exceptions should be processed as OK result for saving session?
It first glance I suggest `HTTPException` with status code less than 400.
What do you think about?

**Comment by imbolc** [comment]
Yes, i think so. But also it would be better to have some configuration
setting to change this behavior at app-level. And something like
`session.rollback()` method at handler-level?

**Comment by asvetlov** [comment]
What's configuration purpose? And what `session.rollback()` should do?

**Comment by imbolc** [comment]
I meant of using settings variable instead of hardcode 400 status code. Rollback mean "forget any changes of session".
```
session_middleware(max_http_status=500, ...)
...
async def handler(request):
    ...
    session['foo'] = 'bar'
    if error:
        session.rollback()
        # session is not saving, although status less than 500
        raise HTTPBadRequest()
```

**Comment by asvetlov** [comment]
Sounds good.
Would you provide a PR?

**Comment by imbolc** [comment]
Done. Without `rollback`, it looks excessive from this perspective :)
