### ISSUE TITLE
Non-cookie-based client-server session contract

### ISSUE THREAD

**Issue by avanov** [aio-libs/aiohttp_session#33]
Hi!

Is there a strong reason why aiohttp_session in its internal API relies strictly on cookies as the only medium to communicate session information to/from clients (https://github.com/aio-libs/aiohttp_session/blob/master/aiohttp_session/__init__.py#L160-L216)?

For instance, I can think of a REST API workflow that uses HTTP headers to provide both a session token and a csrf-preventing token. But in order to implement that kind of API contract, I have to either rely on my own version of a session-handling middleware (that would be about 98-99% similar to aiohttp_session), or go with wrappers around aiohttp_session that extract necessary pieces of information from set cookies and send them in different formats to the client.

I can also think of a possible improvement over that rigidity, by delegating the final implementation of how clients and a server exchange session credentials to a "proxy" ClientServerContract object, that would be constructed during the app initialization step and then used consistently by AbstractStorage (and its derivatives).

**Comment by shicky** [comment]
Hi Maxim,

I am just curious. HTTP being stateless, how would browser know to include custom HTTP header for next request?
Wouldn't you still have to rely on cookie for persistent session data?

**Comment by avanov** [comment]
@shicky, not necessarily.

Some frontend web-frameworks [allow](http://emberjs.com/api/data/classes/DS.RESTAdapter.html#toc_headers-customization) custom headers to be defined application-wide. Another tricky question is - at which particular moment and on what particular event an access (session) token should be registered by the application. And for many applications it is either the very first request to a server (i.e. the one that asks for static assets of the application (I)) or a request that initiates authentication (II). For scenario (I), the access token may be generated and embedded into the application itself, and for (II), it may be passed in a [metadata section] (http://jsonapi.org/format/#document-meta) of the response following the authentication request.

So, the general idea here is that all possible strategies (cookies, http headers, websocket payloads) are orthogonal to code that manages sessions. The only two things this code has to know are 1) how to obtain a session token from a request and, 2) how to communicate changes made to the token (initial assignment, renewal, expiration) back to the client. And I believe that these two are responsibility of a contract-like interface. For instance, the current cookie-based approach can be implemented like this

```python
class HttpCookieContract(ClientServerContract):
    def __init__(self, secret_key, *, cookie_name="AIOHTTP_SESSION",
                 domain=None, max_age=None, path='/',
                 secure=None, httponly=True):
        # ...

    def from_client(self, request):
        # retrieve session credentials from HTTP cookies
   
    def to_client(self, request, response, session):
        # inform client about a change made to the session

    def communicate_assignment(self, request, response, session):
        # calls self.to_client() at some point

    def communicate_expiration(self, request, response, session):
        # calls self.to_client() at some point

    def communicate_update(self, request, response, session):
        # calls self.to_client() at some point, or does nothing, depending on the implementation

```

And then, the current EncryptedCookieStorage (and the base abstract class) will have the following signature
```python
class EncryptedCookieStorage(AbstractStorage):

    def __init__(self, contract=HttpCookieContract):
        super(EncryptedCookieStorage, self).__init__(contract)

    @asyncio.coroutine
    def load_session(self, request):
        credentials = self.contract.from_client(request)
        if credentials is None:
            # ...
        else:
            # ...

    @asyncio.coroutine
    def save_session(self, request, response, session):
        if session.empty:
            return self.contract.communicate_expiration(request, response, session)
        self.contract.communicate_update(request, response, session)
```

For end users, the change will be noticeable only with slightly different initialisation (let's assume RedisStorage):
```python
aiohttp_session.setup(
    app,
    RedisStorage(
        memstore_pool,
        HttpCookieContract(
            cookie_name='cookie-name',
            secure=True,
            httponly=True
        )
    )
)
```

**Comment by asvetlov** [comment]
@avanov 
I afraid you are mixing two different concepts: sessions and security.
`aiohttp_session` is for *HTTP cookies based solutions* only.
For aspects like credentials and permissions please take a look on `aiohttp_security` library.
