### ISSUE TITLE
Description of max_age=None looks wrong

### ISSUE THREAD

**Issue by imbolc** [aio-libs/aiohttp_session#37]
The docs says "max_age - Maximum age for session data, int seconds or None for infinite session.". But  in reality session with `max_age=None` lives until browser is closed.

**Comment by asvetlov** [comment]
I consider it as documentation bug.

@imbolc would you make a PR for doc fix?

**Comment by imbolc** [comment]
Done: #38

**Comment by asvetlov** [comment]
Fixed by #38
