### ISSUE TITLE
typos in examples

### ISSUE THREAD

**Issue by mentaal** [aio-libs/aiohttp_session#39]
In README, there is:
`from cryptorgraphy import fernet` - should be `cryptography`

There is also: `Requires crypotgraphy library:` with a similar typo.

When trying the first example in README, the `trivial usage example`, (and after fixing the typo)
I get: 

`  File "c:\projects\asyncio_venv\lib\site-packages\aiohttp\web.py", line 305, in run_app
    loop = app.loop
AttributeError: 'NoneType' object has no attribute 'loop'`

I am using python 3.5.2 on Anaconda on Windows

**Comment by asvetlov** [comment]
@mentaal thanks very much for a bug report.
I've fixed README, hope it now is good.
