### ISSUE TITLE
Use criptography library instead of PyCrypto

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp_session#6]
https://cryptography.io/

It works on Windows

**Comment by gleb-chipiga** [comment]
PyCrypto has not been updated more than one year https://github.com/dlitz/pycrypto/commits/master

Another good library is PyNaCl https://github.com/pyca/pynacl with SecretBox function http://pynacl.readthedocs.org/en/latest/secret/

**Comment by iho** [comment]
```python
from cryptography.fernet import Fernet
key = Fernet.generate_key()
cipher_suite = Fernet(key)
cipher_text = cipher_suite.encrypt(b"A really secret message. Not for prying eyes.")
plain_text = cipher_suite.decrypt(cipher_text)
```

**Comment by iho** [comment]
Чи може це?
http://cryptography.readthedocs.org/en/latest/hazmat/primitives/symmetric-encryption/#cryptography.hazmat.primitives.ciphers.Cipher

**Comment by asvetlov** [comment]
Done by #16
