### ISSUE TITLE
Fail silently when no key available in session storage

### ISSUE THREAD

**Issue by playpauseandstop** [aio-libs/aiohttp_session#9]
Let's imagine standart approach for getting user ID from request session:

```
@asyncio.coroutine
def get_request_user(request):
    session = yield from get_session(request)
    user_id = session.get(SESSION_USER_KEY)

    if not user_id:
        return None
 
    ...
```

But with ``aiohttp_session==0.1.1`` this makes no sense as ``session.get`` returns session storage instance instead of looking up for key in ``_mapping`` dict. Currenlty in this case I need to use:

```
    try:
         user_id = session[SESSION_USER_KEY]
    except KeyError:
         return None
```

or even

```
    user_id = session._mapping.get(SESSION_USER_KEY)
```

but really prefer to have ``get``, ``setdefault``, and ``update`` methods overriden in session storage, so don't need to call them with ``_mapping`` attribute.

What do you think?

**Comment by asvetlov** [comment]
`get_session` coroutine returns `Session` instance, not storage. Isn't it?

`Session` is derived from `MutableMapping` which provides `get`, `setdefault` etc.

**Comment by playpauseandstop** [comment]
Strange, but it starts working now. But yesterday I'm for sure have behavior when ``session.get`` returns ``session`` instance instead of value from session.

Closing as ``invalid``
